import { Inter } from "next/font/google";
import "./globals.css";
import Banner from "./Components/Layout/Banner";
import Navbar from "./Components/Layout/Navbar";
import Footer from "./Components/Layout/Footer/Footer";
const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="bg-dark">
      <body className={`${inter.className}`}>
        <Banner />
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
